//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNETSample03Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoas
    {
        public int idPessoa { get; set; }
        public string nome { get; set; }
        public string telefone { get; set; }
        public string obs { get; set; }
        public Nullable<int> idCidade { get; set; }
    
        public virtual Cidades Cidades { get; set; }
    }
}
